Uninstall package causing dep conflict
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bitsandbytes 0.47.0 requires torch<3,>=2.2, but you have torch 2.1.2+cu121 which is incompatible.