Fix CTranslate2 version
https://github.com/argosopentech/argos-train/issues/29

This was causing an error

```
ERROR: Could not find a version that satisfies the requirement ctranslate2
```